### ISSUE TITLE
Spigot Bukkit Related Issues

### ISSUE THREAD

**Issue by a3539450** [KettleFoundation/Kettle#19]
[17:25:00] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Residence v4.8.4.4 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_201]
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_201]
        at java.lang.Class.privateGetMethodRecursive(Unknown Source) ~[?:1.8.0_201]
        at java.lang.Class.getMethod0(Unknown Source) ~[?:1.8.0_201]
        at java.lang.Class.getMethod(Unknown Source) ~[?:1.8.0_201]
        at java.lang.Class.getEnumConstantsShared(Unknown Source) ~[?:1.8.0_201]
        at java.lang.Class.enumConstantDirectory(Unknown Source) ~[?:1.8.0_201]
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.ChatColor.valueOf(ChatColor.java:13) ~[ChatColor.class:git-HEAD-e461dd7-dirty]
        at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:845) ~[?:?]
        at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:259) ~[?:?]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:502) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[JavaPlugin.class:git-HEAD-e461dd7-dirty]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [JavaPluginLoader.class:git-HEAD-e461dd7-dirty]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [SimplePluginManager.class:git-HEAD-e461dd7-dirty]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:420) [CraftServer.class:git-HEAD-e461dd7-dirty]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:379) [CraftServer.class:git-HEAD-e461dd7-dirty]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:620) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:581) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:537) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:711) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        ... 23 more
Caused by: java.lang.NullPointerException

Please Help Me

**Comment by GMatrixGames** [comment]
Kettle doesn't include BungeeCord's chat api at all, so plugins that use it, can't load

**Comment by Hexeption** [comment]
Fixed in latest version
