### ISSUE TITLE
Unknown Target Reason when an event watcher sets a mob's attack target.

### ISSUE THREAD

**Issue by Thutmose** [KettleFoundation/Kettle#29]
This occurs when an event handler (listening for LivingUpdateEvent) tries to set the attack target of another mob.

I will get some versions this occurs in tomorrow or so, as it currently is on my development version, which had to be patched to workaround #27 

Affected Kettle: Kettle Unstable 2

It is occuring in Pokecube when the NPC trainers are controlling their mobs, the "AI" is handled seperately from the main mob itself, to make it easier to adapt to any random other mob (Villagers, Cows, Etc can be made to control pokemobs)

```
[23:18:10] [Server thread/WARN] [Minecraft]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.entity.EntityLiving.setAttackTarget(EntityLiving.java:197) [vq.class:?]
	at net.minecraft.entity.EntityLiving.func_70624_b(EntityLiving.java:187) [vq.class:?]
	at pokecube.adventures.ai.tasks.AIBattle.checkPokemobTarget(AIBattle.java:63) [AIBattle.class:?]
	at pokecube.adventures.ai.tasks.AIBattle.updateTask(AIBattle.java:254) [AIBattle.class:?]
	at pokecube.adventures.ai.tasks.AIBattle.doMainThreadTick(AIBattle.java:49) [AIBattle.class:?]
	at thut.api.entity.ai.AIThreadManager$AIStuff.runServerThreadTasks(AIThreadManager.java:78) [AIThreadManager$AIStuff.class:?]
	at thut.api.entity.ai.AIThreadManager.updateEntityActionState(AIThreadManager.java:352) [AIThreadManager.class:?]
	at thut.api.entity.ai.AIThreadManager.LivingUpdate(AIThreadManager.java:345) [AIThreadManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_44_AIThreadManager_LivingUpdate_LivingUpdateEvent.invoke(.dynamic) [?:git-HEAD-b7c2f7d]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:git-HEAD-b7c2f7d]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:git-HEAD-b7c2f7d]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:575) [ForgeHooks.class:git-HEAD-b7c2f7d]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2416) [vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:339) [vq.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2267) [amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2228) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2012) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:836) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:464) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:736) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:617) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Thutmose** [comment]
Still occurs when called directly via the EntityAIBase, rather than going through an event listener:

```
[15:15:01] [Server thread/WARN] [Minecraft]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.entity.EntityLiving.setAttackTarget(EntityLiving.java:197) [vq.class:?]
	at net.minecraft.entity.EntityLiving.func_70624_b(EntityLiving.java:187) [vq.class:?]
	at pokecube.adventures.ai.tasks.AIBattle.checkPokemobTarget(AIBattle.java:63) [AIBattle.class:?]
	at pokecube.adventures.ai.tasks.AIBattle.updateTask(AIBattle.java:254) [AIBattle.class:?]
	at pokecube.adventures.ai.tasks.AIBattle.doMainThreadTick(AIBattle.java:49) [AIBattle.class:?]
	at thut.api.entity.ai.AIThreadManager$AIStuff.runServerThreadTasks(AIThreadManager.java:78) [AIThreadManager$AIStuff.class:?]
	at thut.api.entity.ai.EntityAIBaseManager.updateEntityActionState(EntityAIBaseManager.java:43) [EntityAIBaseManager.class:?]
	at thut.api.entity.ai.EntityAIBaseManager.func_75246_d(EntityAIBaseManager.java:36) [EntityAIBaseManager.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [xf.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:824) [vq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2685) [vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:630) [vq.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:182) [vd.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2502) [vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:339) [vq.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2267) [amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2228) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2012) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:836) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:464) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:736) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:617) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```
