### ISSUE TITLE
error with openterraingenerator

### ISSUE THREAD

**Issue by Cronosus** [KettleFoundation/Kettle#30]
Hi, when server start then i get error while enabling plugin OpenTerrainGenerator

`[19:11:20] [Server thread/ERROR] [Minecraft]: Error occurred while enabling OpenTerrainGenerator v1.12.2 v6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/WorldGenFactory
        at com.pg85.otg.bukkit.OTGPlugin.onEnable(OTGPlugin.java:85) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[JavaPlugin.class:git-HEAD-b7c2f7d]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [JavaPluginLoader.class:git-HEAD-b7c2f7d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [SimplePluginManager.class:git-HEAD-b7c2f7d]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:421) [CraftServer.class:git-HEAD-b7c2f7d]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:380) [CraftServer.class:git-HEAD-b7c2f7d]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:256) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:581) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.WorldGenFactory
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:git-HEAD-b7c2f7d]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:99) ~[PluginClassLoader.class:git-HEAD-b7c2f7d]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 9 more`

any tips?

**Comment by Cronosus** [comment]
ad. working on Kettle Dev HEAD-a8543ec

**Comment by GMatrixGames** [comment]
This has been fixed in the next build!

- GMatrixGames
