### ISSUE TITLE
Kettle Issue With SkyFactory 4.0.5

### ISSUE THREAD

**Issue by jbreadtoasted** [KettleFoundation/Kettle#31]
I really want to be able to use Kettle for moded servers and i really hope to see it grow because i miss bukkit forge i miss kcauldron mcpc+ lets get it back on track for the awesome gaming community and see where it takes us!!!!
----------------------------------------------------------------------------------------------------------

`[12:45:08] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FastWorkbench (fastbench)
 
Caused by: java.lang.UnsupportedOperationException: Cannot redefine singleton Server
        at org.bukkit.Bukkit.setServer(Bukkit.java:79) ~[Bukkit.class:git-HEAD-b7c2f7d]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.<init>(CraftServer.java:245) ~[CraftServer.class:git-HEAD-b7c2f7d]
        at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:129) ~[pl.class:?]
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:14) ~[ny.class:?]
        at shadows.fastbench.net.HijackedDedicatedPlayerList.<init>(HijackedDedicatedPlayerList.java:13) ~[HijackedDedicatedPlayerList.class:?]
        at shadows.fastbench.proxy.BenchServerProxy.replacePlayerList(BenchServerProxy.java:19) ~[BenchServerProxy.class:?]
        at shadows.fastbench.FastBench.serverStartRemoval(FastBench.java:102) ~[FastBench.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624) ~[kettle_latest.jar:git-HEAD-b7c2f7d]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[kettle_latest.jar:git-HEAD-b7c2f7d]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[kettle_latest.jar:git-HEAD-b7c2f7d]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:git-HEAD-b7c2f7d]
        at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:854) ~[Loader.class:git-HEAD-b7c2f7d]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:293) ~[FMLCommonHandler.class:git-HEAD-b7c2f7d]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:581) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[12:45:08] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\Taz\Desktop\Kettle\.\crash-reports\crash-2019-05-08_12.45.08-server.txt
[12:45:08] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[12:45:08] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[12:45:08] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[12:45:08] [Server thread/INFO] [fluxnetworks]: Cleared Network Caches
[12:45:08] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up all world data: 0 data blobs
[12:45:08] [Server thread/WARN] [opencomputers]: Error handling file saving: Did the server never start?
[12:45:08] [Server thread/INFO] [Parabox]: Saving Parabox world data.
[12:45:08] [Server thread/WARN] []: Exception in thread "Server thread"
[12:45:08] [Server thread/WARN] []: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Parabox (parabox)
[12:45:08] [Server thread/WARN] []: Caused by: java.lang.NullPointerException
[12:45:08] [Server thread/WARN] []:     at net.darkhax.parabox.util.WorldSpaceTimeManager.onGameInstanceClose(WorldSpaceTimeManager.java:64)
[12:45:08] [Server thread/WARN] []:     at net.darkhax.parabox.Parabox.serverStop(Parabox.java:85)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at java.lang.reflect.Method.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at java.lang.reflect.Method.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[12:45:08] [Server thread/WARN] []:     at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at java.lang.reflect.Method.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[12:45:08] [Server thread/WARN] []:     at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:847)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:509)
[12:45:08] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:661)
[12:45:08] [Server thread/WARN] []:     at java.lang.Thread.run(Unknown Source)
>
RAW Paste Data
[12:45:08] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FastWorkbench (fastbench)

Caused by: java.lang.UnsupportedOperationException: Cannot redefine singleton Server
        at org.bukkit.Bukkit.setServer(Bukkit.java:79) ~[Bukkit.class:git-HEAD-b7c2f7d]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.<init>(CraftServer.java:245) ~[CraftServer.class:git-HEAD-b7c2f7d]
        at net.minecraft.server.management.PlayerList.<init>(PlayerList.java:129) ~[pl.class:?]
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:14) ~[ny.class:?]
        at shadows.fastbench.net.HijackedDedicatedPlayerList.<init>(HijackedDedicatedPlayerList.java:13) ~[HijackedDedicatedPlayerList.class:?]
        at shadows.fastbench.proxy.BenchServerProxy.replacePlayerList(BenchServerProxy.java:19) ~[BenchServerProxy.class:?]
        at shadows.fastbench.FastBench.serverStartRemoval(FastBench.java:102) ~[FastBench.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624) ~[kettle_latest.jar:git-HEAD-b7c2f7d]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[kettle_latest.jar:git-HEAD-b7c2f7d]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[kettle_latest.jar:git-HEAD-b7c2f7d]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:git-HEAD-b7c2f7d]
        at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:854) ~[Loader.class:git-HEAD-b7c2f7d]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:293) ~[FMLCommonHandler.class:git-HEAD-b7c2f7d]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:581) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[12:45:08] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\Taz\Desktop\Kettle\.\crash-reports\crash-2019-05-08_12.45.08-server.txt
[12:45:08] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[12:45:08] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[12:45:08] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[12:45:08] [Server thread/INFO] [fluxnetworks]: Cleared Network Caches
[12:45:08] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up all world data: 0 data blobs
[12:45:08] [Server thread/WARN] [opencomputers]: Error handling file saving: Did the server never start?
[12:45:08] [Server thread/INFO] [Parabox]: Saving Parabox world data.
[12:45:08] [Server thread/WARN] []: Exception in thread "Server thread"
[12:45:08] [Server thread/WARN] []: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Parabox (parabox)
[12:45:08] [Server thread/WARN] []: Caused by: java.lang.NullPointerException
[12:45:08] [Server thread/WARN] []:     at net.darkhax.parabox.util.WorldSpaceTimeManager.onGameInstanceClose(WorldSpaceTimeManager.java:64)
[12:45:08] [Server thread/WARN] []:     at net.darkhax.parabox.Parabox.serverStop(Parabox.java:85)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at java.lang.reflect.Method.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at java.lang.reflect.Method.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[12:45:08] [Server thread/WARN] []:     at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at java.lang.reflect.Method.invoke(Unknown Source)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[12:45:08] [Server thread/WARN] []:     at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[12:45:08] [Server thread/WARN] []:     at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:847)
[12:45:08] [Server thread/WARN] []:     at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:509)
[12:45:08] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:661)
[12:45:08] [Server thread/WARN] []:     at java.lang.Thread.run(Unknown Source)
>
`

**Comment by josephworks** [comment]
I have the same issue. For now, just remove FastWorkbench

**Comment by Timardo** [comment]
FastWorkbecnch tries to create new PlayerList type, there is the problem, during its init the Bukkit's server singleton is created, which is allowed only once. I added a condition to create it only once in PR

**Comment by Redd56** [comment]
Pastebin
