### ISSUE TITLE
Exception ticking world crash while checking the state of grass

### ISSUE THREAD

**Issue by infinitephantasm** [KettleFoundation/Kettle#38]
```
java.lang.NullPointerException: Exception ticking world
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:280)
	at net.minecraft.block.BlockGrass.func_180650_b(BlockGrass.java:51)
	at net.minecraft.block.Block.func_180645_a(Block.java:505)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:699)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:426)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:464)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:617)
	at java.lang.Thread.run(Unknown Source)
```

unsure why this happens, but it occurs after the server's left on for a while.
[crash-2019-06-12_13.49.17-server.txt](https://github.com/KettleFoundation/Kettle/files/3284629/crash-2019-06-12_13.49.17-server.txt)

**Comment by Redd56** [comment]
👏paste👏bin👏

**Comment by infinitephantasm** [comment]
[crash report paste](https://pastebin.com/pMEUH9RH)

**Comment by Redd56** [comment]
That was... Fast

**Comment by infinitephantasm** [comment]
having email notifications and a phone that pings me about emails helps

**Comment by Redd56** [comment]
Same. Also that level name is the exactly my reaction to that crash report... Like how did that

**Comment by Timardo** [comment]
This is the same issue as in #32, which has already been resolved.
