### ISSUE TITLE
Error Mod Wings can't run

### ISSUE THREAD

**Issue by HearthunterPro** [KettleFoundation/Kettle#40]
Sorry I give error wong, this is true Error in below ---

**Comment by Timardo** [comment]
`[15:51:35] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod wings (Wings) requires [llibrary@[1.7,1.8)]`

Are you sure you have the llibrary mod installed?

**Comment by HearthunterPro** [comment]
Yes I have in folder mod

> `[15:51:35] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod wings (Wings) requires [llibrary@[1.7,1.8)]`
> 
> Are you sure you have the llibrary mod installed?

Yes I have in folder mod

**Comment by HearthunterPro** [comment]
Sorry I give error wong, this true Error:


[20:26:58] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[20:26:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[20:26:58] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2812 for Minecraft 1.12.2 loading
[20:26:58] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_211, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_211
[20:26:58] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[20:26:58] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[20:26:58] [main/INFO] [FML]: Searching C:\Users\Administrator\Desktop\G\.\mods for mods
[20:26:58] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in wings-1.1.4-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:26:58] [main/WARN] [FML]: The coremod wings (me.paulf.wings.server.asm.plugin.WingsLoadingPlugin) is not signed!
[20:26:58] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:26:58] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:26:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:26:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:26:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:27:01] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[20:27:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:27:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:27:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:27:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:27:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:27:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:27:03] [main/WARN] [LLibrary Core]: Failed to fetch hierarchy node for net.minecraft.entity.player.EntityPlayerMP. This may cause patch issues
[20:27:03] [main/WARN] [LLibrary Core]: Failed to fetch hierarchy node for net.minecraft.entity.EntityLivingBase. This may cause patch issues
[20:27:03] [main/WARN] [LLibrary Core]: Failed to fetch hierarchy node for net.minecraft.nbt.NBTTagList. This may cause patch issues
[20:27:03] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[20:27:03] [main/INFO] [STDOUT]: [org.bukkit.craftbukkit.v1_12_R1.Main:main:192]: Loading libraries, please wait...
[20:27:09] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [kettle.jar:git-HEAD-b7c2f7d]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:35) [kettle.jar:git-HEAD-b7c2f7d]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/entity/player/EntityPlayer.func_71059_n(Lnet/minecraft/entity/Entity;)V @1320: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[3]) is not assignable to 'net/minecraft/entity/Entity'
  Current Frame:
    bci: @1320
    flags: { }
    locals: { 'net/minecraft/entity/player/EntityPlayer', 'net/minecraft/entity/Entity', float, float, float, integer, integer, integer, integer, 'net/minecraftforge/event/entity/player/CriticalHitEvent', integer, double, double_2nd, float, integer, integer, top, double, double_2nd, double, double_2nd, double, double_2nd, integer, 'net/minecraft/item/ItemStack', 'java/lang/Object', float }
    stack: { uninitialized 1310, uninitialized 1310, 'org/bukkit/craftbukkit/v1_12_R1/entity/CraftHumanEntity', 'java/lang/Object' }
  Bytecode:
    0x0000000: 2a2b b807 689a 0004 b12b b607 6b99 05d4
    0x0000010: 2b2a b607 6e9a 05cc 2ab2 0157 b601 69b9
    0x0000020: 030e 0100 9045 2bc1 0004 9900 152a b602
    0x0000030: 192b c000 04b6 0772 b807 7646 a700 0e2a
    0x0000040: b602 19b2 077c b807 7646 2a13 035c b607
    0x0000050: 7f38 0424 1302 4c17 0417 046a 1303 2f6a
    0x0000060: 626a 4525 1704 6a46 2ab6 0223 240b 959d
    0x0000070: 0009 250b 959e 056c 1704 1307 8095 9e00
    0x0000080: 0704 a700 0403 3605 0336 0603 3607 1507
    0x0000090: 2ab8 0783 6036 072a b603 0899 002e 1505
    0x00000a0: 9900 292a b401 bd01 c000 022a b401 fe2a
    0x00000b0: b402 0e2a b402 0bb2 0786 2ab6 0289 0c0c
    0x00000c0: b602 8d84 0701 0436 0615 0599 003d 2ab4
    0x00000d0: 035b 0b95 9e00 342a b401 b39a 002d 2ab6
    0x00000e0: 0789 9a00 262a b603 5f9a 001f 2ab2 078c
    0x00000f0: b604 f39a 0015 2ab6 029f 9a00 0e2b c100
    0x0000100: 0499 0007 04a7 0004 0336 0815 0899 000e
    0x0000110: 2ab6 0308 9a00 0704 a700 0403 3608 2a2b
    0x0000120: 1508 1508 9900 0913 078d a700 040c b807
    0x0000130: 913a 0919 09c6 0007 04a7 0004 0336 0815
    0x0000140: 0899 000b 2419 09b6 0796 6a45 2425 6245
    0x0000150: 0336 0a2a b407 992a b407 9c66 8d39 0b15
    0x0000160: 0599 0036 1508 9a00 3115 069a 002c 2ab4
    0x0000170: 01b3 9900 2518 0b2a b607 9f8d 989c 001a
    0x0000180: 2ab2 06b7 b607 433a 0d19 0db6 0428 c107
    0x0000190: a199 0006 0436 0a0b 380d 0336 0e2a b807
    0x00001a0: a436 0f2b c100 0499 0048 2bc0 0004 b607
    0x00001b0: a538 0d15 0f9e 003a 2bb6 07a6 9a00 33bb
    0x00001c0: 07a8 592a b604 6e2b b607 ab04 b707 ae3a
    0x00001d0: 10b8 07b1 1910 b904 8a02 0019 10b6 07b2
    0x00001e0: 9a00 0f04 360e 2b19 10b6 07b5 b607 b82b
    0x00001f0: b407 b939 112b b407 ba39 132b b407 bb39
    0x0000200: 152b 2ab8 07bf 24b6 07c0 3617 1517 9903
    0x0000210: 9915 079e 0082 2bc1 0004 9900 2e2b c000
    0x0000220: 042a 1507 8613 035c 6a2a b402 a913 03e4
    0x0000230: 6ab8 03eb 8d2a b402 a913 03e4 6ab8 03e8
    0x0000240: 768d b607 c4a7 0033 2b2a b402 a913 03e4
    0x0000250: 6ab8 03eb 7615 0786 6a13 035c 6a8d 1407
    0x0000260: c52a b402 a913 03e4 6ab8 03e8 1507 866a
    0x0000270: 1303 5c6a 8db6 07c9 2a59 b403 1514 07ca
    0x0000280: 6bb5 0315 2a59 b403 1814 07ca 6bb5 0318
    0x0000290: 2a03 b607 ce15 0a99 00bb 0c2a b807 d224
    0x00002a0: 6a62 3818 2ab4 01bd 1204 2bb6 0335 0f14
    0x00002b0: 0244 0fb6 033d b607 d6b9 07d7 0100 3a19
    0x00002c0: 1919 b905 f901 0099 0067 1919 b905 fd01
    0x00002d0: 00c0 0004 3a1a 191a 2aa5 0052 191a 2ba5
    0x00002e0: 004c 2a19 1ab6 07da 9a00 432a 191a b607
    0x00002f0: de14 07df 989c 0036 191a 2ab8 07bf b607
    0x0000300: e417 18b6 064a 9900 2519 1a2a 1303 2b2a
    0x0000310: b402 a913 03e4 6ab8 03eb 8d2a b402 a913
    0x0000320: 03e4 6ab8 03e8 768d b607 c4a7 ff95 2ab4
    0x0000330: 01bd 01c0 0002 2ab4 01fe 2ab4 020e 2ab4
    0x0000340: 020b b207 e72a b602 890c 0cb6 028d 2ab6
    0x0000350: 07ea 2bc1 0661 9900 9b2b b407 ed99 0094
    0x0000360: 0336 182b b607 abc0 0470 3a19 bb07 ef59
    0x0000370: 1811 1813 1815 b707 f13a 1abb 07f3 5919
    0x0000380: 1919 1ab6 07f7 b707 fa3a 1b2a b401 bdb6
    0x0000390: 0476 b604 8419 1bb9 048a 0200 191b b607
    0x00003a0: fb99 0009 0436 18a7 001c 191a 191b b607
    0x00003b0: feb6 07ff 9a00 0f19 1919 1bb6 07fe b908
    0x00003c0: 0302 0015 189a 002c 2bc0 0661 b408 07bb
    0x00003d0: 0809 592b b708 0ab6 0810 2b03 b507 ed2b
    0x00003e0: 1811 b507 b92b 1813 b507 ba2b 1815 b507
    0x00003f0: bb15 0899 0028 2ab4 01bd 01c0 0002 2ab4
    0x0000400: 01fe 2ab4 020e 2ab4 020b b208 132a b602
    0x0000410: 890c 0cb6 028d 2a2b b608 1615 089a 0050
    0x0000420: 150a 9a00 4b15 0599 0026 2ab4 01bd 01c0
    0x0000430: 0002 2ab4 01fe 2ab4 020e 2ab4 020b b208
    0x0000440: 192a b602 890c 0cb6 028d a700 232a b401
    0x0000450: bd01 c000 022a b401 fe2a b402 0e2a b402
    0x0000460: 0bb2 081c 2ab6 0289 0c0c b602 8d25 0b95
    0x0000470: 9e00 082a 2bb6 081f 2a2b b608 222b c100
    0x0000480: 0499 000b 2bc0 0004 2ab8 0826 2a2b b808
    0x0000490: 292a b602 193a 182b 3a19 2bc1 082b 9900
    0x00004a0: 1b2b c008 2bb4 082f 3a1a 191a c100 0499
    0x00004b0: 000a 191a c000 043a 1919 18b6 0226 9a00
    0x00004c0: 3819 19c1 0004 9900 3019 18b6 0229 3a1a
    0x00004d0: 1918 1919 c000 042a b608 3319 18b6 0226
    0x00004e0: 9900 162a 191a b206 b7b8 06b1 2ab2 06b7
    0x00004f0: b200 c9b6 0758 2bc1 0004 9900 a317 0d2b
    0x0000500: c000 04b6 07a5 6638 1a2a b208 3617 1a13
    0x0000510: 0707 6ab8 070a b604 bd15 0f9e 0035 bb07
    0x0000520: a859 2ab6 046e 1919 b607 ab15 0f07 68b7
    0x0000530: 07ae 3a1b b807 b119 1bb9 048a 0200 191b
    0x0000540: b607 b29a 000d 1919 191b b607 b5b6 07b8
    0x0000550: 2ab4 01bd c108 3899 0046 171a 0d95 9e00
    0x0000560: 3f17 1a8d 1401 1f6b 8e36 1b2a b401 bdc0
    0x0000570: 0838 b208 3e2b b408 3f2b b408 402b b408
    0x0000580: 4113 035c 6a8d 632b b408 4215 1b14 07c5
    0x0000590: 0e14 07c5 1408 4303 bc0a b608 482a 1303
    0x00005a0: 2ab6 06f5 a700 3d2a b401 bd01 c000 022a
    0x00005b0: b401 fe2a b402 0e2a b402 0bb2 084b 2ab6
    0x00005c0: 0289 0c0c b602 8d15 0e99 0007 2bb6 084c
    0x00005d0: 2ac1 0661 9900 0d2a c006 61b6 0664 b608
    0x00005e0: 4fb1                                   
  Stackmap Table:
    same_frame(@9)
    append_frame(@63,Float)
    append_frame(@74,Float)
    append_frame(@120,Float)
    same_frame(@133)
    same_locals_1_stack_item_frame(@134,Integer)
    append_frame(@201,Integer,Integer,Integer)
    same_frame(@264)
    same_locals_1_stack_item_frame(@265,Integer)
    append_frame(@283,Integer)
    same_locals_1_stack_item_frame(@284,Integer)
    full_frame(@301,{Object[#2],Object[#817],Float,Float,Float,Integer,Integer,Integer,Integer},{Object[#2],Object[#817],Integer})
    full_frame(@302,{Object[#2],Object[#817],Float,Float,Float,Integer,Integer,Integer,Integer},{Object[#2],Object[#817],Integer,Float})
    append_frame(@316,Object[#1939])
    same_locals_1_stack_item_frame(@317,Integer)
    same_frame(@332)
    append_frame(@407,Integer,Double)
    append_frame(@495,Float,Integer,Integer)
    full_frame(@584,{Object[#2],Object[#817],Float,Float,Float,Integer,Integer,Integer,Integer,Object[#1939],Integer,Double,Float,Integer,Integer,Top,Double,Double,Double,Integer},{})
    same_frame(@632)
    same_frame(@661)
    append_frame(@704,Float,Object[#1526])
    append_frame(@811,Object[#4])
    chop_frame(@814,1)
    chop_frame(@850,2)
    full_frame(@938,{Object[#2],Object[#817],Float,Float,Float,Integer,Integer,Integer,Integer,Object[#1939],Integer,Double,Float,Integer,Integer,Top,Double,Double,Double,Integer,Integer,Object[#1136],Object[#2031],Object[#2035]},{})
    same_frame(@963)
    full_frame(@1009,{Object[#2],Object[#817],Float,Float,Float,Integer,Integer,Integer,Integer,Object[#1939],Integer,Double,Float,Integer,Integer,Top,Double,Double,Double,Integer},{})
    same_frame(@1051)
    same_frame(@1101)
    same_frame(@1133)
    same_frame(@1144)
    same_frame(@1164)
    append_frame(@1209,Object[#198],Object[#3044])
    same_frame(@1270)
    append_frame(@1360,Float)
    chop_frame(@1437,1)
    chop_frame(@1447,2)
    same_frame(@1488)
    full_frame(@1505,{Object[#2],Object[#817]},{})

	at net.minecraft.util.datafix.DataFixesManager.func_188279_a(DataFixesManager.java:170) ~[rz.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1547) ~[MinecraftServer.class:?]
	... 12 more
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: java.lang.reflect.InvocationTargetException
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:35)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.Runtime.exit(Unknown Source)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.System.exit(Unknown Source)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:27:09] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	... 6 more

**Comment by Hexeption** [comment]
This is not a Kettle Bug 
![image](https://user-images.githubusercontent.com/4052647/60397933-7f788200-9b4a-11e9-9429-a6ae9fb43e07.png)

**Comment by HearthunterPro** [comment]
But in folder server mod not have anything except Wing and LLibrary.
![image](https://user-images.githubusercontent.com/29220658/60397948-178f5f00-9b7d-11e9-98ad-a542990bbc77.png)
