### ISSUE TITLE
Crash with Apple Core

### ISSUE THREAD

**Issue by Nick-77ab2** [KettleFoundation/Kettle#50]
I initially used the latest dev build, but then switched to the latest unstable build (3). Both crashed due to the same issue, but at different segments. I'm running a large modpack and the initial problem is Galacticraft missing a bytecode injection, and the crash states that Applecore is also at fault. This crash doesn't happen on a regular forge server. There is no actual crash report so I had to grab it from the latest log.

[12:13:59] [main/INFO] [STDERR]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1741]: Potential problem: Galacticraft did not complete injection of bytecode into: pl (2 / 4)
[12:13:59] [main/INFO] [Quark ASM]: Transforming net.minecraft.entity.Entity
[12:13:59] [main/INFO] [Quark ASM]: Applying Transformation to method (Names [move, func_70091_d] Descriptor (Lnet/minecraft/entity/MoverType;DDD)V)
[12:13:59] [main/INFO] [Quark ASM]: Located Method, patching...
[12:13:59] [main/INFO] [Quark ASM]: Located patch target node INVOKEVIRTUAL net/minecraft/entity/Entity.func_184231_a (DZLnet/minecraft/block/state/IBlockState;Lnet/minecraft/util/math/BlockPos;)V
[12:13:59] [main/INFO] [Quark ASM]: Patch result: true
[12:13:59] [main/INFO] [Quark ASM]: Located Method, patching...
[12:13:59] [main/INFO] [Quark ASM]: Located patch target node INVOKEVIRTUAL net/minecraft/entity/Entity.func_145775_I ()V
[12:13:59] [main/INFO] [Quark ASM]: Patch result: true
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: java.lang.reflect.InvocationTargetException
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at java.lang.reflect.Method.invoke(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:73)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:37)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at java.lang.Class.getDeclaredMethods0(Native Method)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at java.lang.Class.privateGetMethodRecursive(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at java.lang.Class.getMethod0(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at java.lang.Class.getMethod(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:13:59] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: ... 6 more
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at java.lang.ClassLoader.loadClass(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at java.lang.ClassLoader.loadClass(Unknown Source)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: ... 13 more
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer squeek.applecore.asm.TransformerModuleHandler@43cf5bff from coremod AppleCore
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: ... 15 more
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: java.lang.RuntimeException: EntityPlayer.addExhaustion call pattern (index=1) not found in net/minecraft/entity/player/EntityPlayer.func_70664_aZ
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: at squeek.applecore.asm.module.ModuleExhaustingActions.patchSimpleAddExhaustionCall(ModuleExhaustingActions.java:129)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: at squeek.applecore.asm.module.ModuleExhaustingActions.transform(ModuleExhaustingActions.java:30)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:42)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
[12:13:59] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: ... 17 more

**Comment by Nick-77ab2** [comment]
Here's a screenshot of the specific issue that is occurring as found by micdoodle8 
![Screenshot_1](https://user-images.githubusercontent.com/8357073/62497822-b02f8500-b7a2-11e9-98f9-995b9742cb8c.png)

**Comment by Nick-77ab2** [comment]
And is this post just getting ignore or what?

**Comment by GMatrixGames** [comment]
This should be fixed in the next update, will do some testing

- GMatrixGames

**Comment by GMatrixGames** [comment]
EDIT: FIXED

**Comment by Teoxex** [comment]
Hi everyone, I have encountered the same problem too, every time I try to start my server it gives me this error: https://pastebin.com/tWmGUhPs .
Apparently it seems a Galacticraft problem by the way "EntityPlayerMP" (Maybe the animation of when you are in space goes against something? I don't know, I'm not a java expert). Would anyone know how to help me? Thanks. (If you are about to write that Mohist is the problem, I don't think because he gave the same error with Sponge and Magma)

**Comment by josephworks** [comment]
@Teoxex make a ticket in magma and mohist. You can also create a ticket here, but nothing will be done about it.
