### ISSUE TITLE
Crash on start [Unable to launch]

### ISSUE THREAD

**Issue by AlexCreeper25** [KettleFoundation/Kettle#54]
Getting this error when starting the server:

`[15:25:21] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:73) [server.jar:git-HEAD-26a18ca]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:37) [server.jar:git-HEAD-26a18ca]
Caused by: java.lang.NoClassDefFoundError: jline/console/ConsoleReader
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:204) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:79) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1544) ~[MinecraftServer.class:?]
	... 12 more
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: java.lang.reflect.InvocationTargetException
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:73)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:37]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:37)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at java.lang.Runtime.exit(Runtime.java:107)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at java.lang.System.exit(System.java:971)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:25:21] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:78]: 	... 6 more
`

**Comment by GMatrixGames** [comment]
Issue will be fixed in the next full update.

- GMatrixGames

**Comment by Timardo** [comment]
Here is hastebin for better readability: https://hastebin.com/eqicidusoz.md

Next time please use the issue template to speed up process of fixing

**Comment by GMatrixGames** [comment]
I think when he made it, there was no template lol

**Comment by GMatrixGames** [comment]
This has been fixed in the next build!

- GMatrixGames
