### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by PulseBeat02** [KettleFoundation/Kettle#59]
Hi, while I was starting up my server, I got the following error:

`[14:55:45] [main/WARN] [mixin]: Mixin config mixins.sgcraft.json requires mixin subsystem version 0.7.10 but 0.6.6 was found. The mixin config will not be applied.
A problem occurred running the Server launcher.[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: java.lang.reflect.InvocationTargetException
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]:       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]:       at java.lang.reflect.Method.invoke(Unknown Source)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:35)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.sgcraft.json requires mixin subsystem version 0.7.10
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:358)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:296)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:790)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:88)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:75)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:256)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:54)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:99)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.launch.platform.MixinPlatformManager.prepare(MixinPlatformManager.java:141)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.launch.MixinBootstrap.doInit(MixinBootstrap.java:188)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at org.spongepowered.asm.launch.MixinTweaker.acceptOptions(MixinTweaker.java:53)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:55:45] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        ... 6 more
Press any key to continue . . .`

It looks like there is a problem with mixin. These are my log files:

[latest.log](https://github.com/KettleFoundation/Kettle/files/3538493/latest.log)
[debug.log](https://github.com/KettleFoundation/Kettle/files/3538494/debug.log)

If anyone knows the solution, please reach out to me quick.

**Comment by GMatrixGames** [comment]
You need a different version of Mixins for that mod, it doesn't have anything to do with Kettle as we don't use Mixins

**Comment by PulseBeat02** [comment]
@GMatrixGames What mod though? I have no idea what the mod is.

**Comment by PulseBeat02** [comment]
@GMatrixGames How would we change the Mixins then?

**Comment by GMatrixGames** [comment]
The mod developer of "sgcraft"'s json file, needs to update it
