### ISSUE TITLE
Crash whenever i switch to tab 2

### ISSUE THREAD

**Issue by Zempat** [KettleFoundation/Kettle#61]
So whenever i switch to tab 2 (2/2) the game goes to the "Shutting Down Server" screen, then crashes, Here's the crash report. ---- Minecraft Crash Report ----

WARNING: coremods are present:
  weaponlib (mw_2.0-0.4.1_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 8/28/19 12:19 PM
Description: Rendering item

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.func_188616_a(CompatibleWeaponRenderer.java:144)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.renderer.RenderItem.func_180450_b(RenderItem.java:336)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.func_188616_a(CompatibleWeaponRenderer.java:144)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)

-- Item being rendered --
Details:
	Item Type: com.vicmatskiv.weaponlib.Weapon@5d63295e
	Registry Name: mw:m16a4
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.renderer.RenderItem.func_180450_b(RenderItem.java:336)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (345, 25). Absolute: (1728, 1244)
	Screen size: Scaled: (512, 275). Absolute: (2560, 1373). Scale factor of 5

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Zempat'/1759, l='MpServer', x=161.50, y=64.00, z=65.50]]
	Chunk stats: MultiplayerChunkCache: 574, 574
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (159,64,63), Chunk: (at 15,4,15 in 9,3; contains blocks 144,0,48 to 159,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 123 game time, 123 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 88 total; [EntityCow['Cow'/55, l='MpServer', x=82.50, y=67.00, z=-9.50], EntityCow['Cow'/56, l='MpServer', x=82.57, y=67.00, z=-11.30], EntityCow['Cow'/57, l='MpServer', x=83.50, y=67.00, z=-11.50], EntityCow['Cow'/58, l='MpServer', x=80.45, y=67.00, z=-11.13], EntityChicken['Chicken'/59, l='MpServer', x=102.50, y=63.00, z=14.50], EntityChicken['Chicken'/60, l='MpServer', x=97.87, y=65.00, z=26.14], EntityChicken['Chicken'/61, l='MpServer', x=101.37, y=64.00, z=21.40], EntityChicken['Chicken'/62, l='MpServer', x=91.50, y=67.00, z=50.50], EntityChicken['Chicken'/63, l='MpServer', x=91.50, y=67.00, z=50.50], EntityChicken['Chicken'/64, l='MpServer', x=88.40, y=67.00, z=46.21], EntityChicken['Chicken'/65, l='MpServer', x=87.57, y=67.00, z=47.44], EntityChicken['Chicken'/66, l='MpServer', x=107.50, y=63.00, z=50.50], EntityChicken['Chicken'/67, l='MpServer', x=104.50, y=63.00, z=46.50], EntityChicken['Chicken'/68, l='MpServer', x=104.50, y=63.00, z=51.50], EntityPig['Pig'/69, l='MpServer', x=105.59, y=72.00, z=124.12], EntityPig['Pig'/70, l='MpServer', x=110.50, y=70.00, z=130.50], EntityPig['Pig'/71, l='MpServer', x=115.49, y=68.00, z=126.78], EntityPig['Pig'/72, l='MpServer', x=111.45, y=69.00, z=130.47], EntityChicken['Chicken'/78, l='MpServer', x=124.50, y=66.00, z=96.50], EntityChicken['Chicken'/79, l='MpServer', x=128.50, y=65.00, z=95.50], EntityChicken['Chicken'/80, l='MpServer', x=131.50, y=65.00, z=96.50], EntityChicken['Chicken'/81, l='MpServer', x=132.50, y=65.00, z=97.50], EntityChicken['Chicken'/86, l='MpServer', x=160.38, y=64.00, z=64.71], EntityChicken['Chicken'/87, l='MpServer', x=159.50, y=64.00, z=64.50], EntityChicken['Chicken'/88, l='MpServer', x=167.24, y=64.00, z=63.49], EntityChicken['Chicken'/89, l='MpServer', x=159.70, y=64.00, z=56.05], EntityChicken['Chicken'/90, l='MpServer', x=173.79, y=63.00, z=77.57], EntityChicken['Chicken'/91, l='MpServer', x=182.50, y=64.00, z=77.50], EntityChicken['Chicken'/92, l='MpServer', x=174.37, y=63.00, z=78.54], EntityChicken['Chicken'/93, l='MpServer', x=172.50, y=63.00, z=78.17], EntityChicken['Chicken'/94, l='MpServer', x=170.50, y=64.00, z=73.50], EntityChicken['Chicken'/95, l='MpServer', x=174.50, y=64.00, z=72.50], EntityChicken['Chicken'/96, l='MpServer', x=173.50, y=64.00, z=74.50], EntityChicken['Chicken'/97, l='MpServer', x=168.50, y=63.00, z=124.50], EntityChicken['Chicken'/98, l='MpServer', x=169.53, y=64.00, z=123.80], EntityChicken['Chicken'/99, l='MpServer', x=174.50, y=65.00, z=134.39], EntityBat['Bat'/4195, l='MpServer', x=205.17, y=34.52, z=30.09], EntityChicken['Chicken'/100, l='MpServer', x=171.50, y=64.00, z=123.50], EntityHorse['Horse'/117, l='MpServer', x=191.50, y=67.00, z=21.50], EntityHorse['Horse'/118, l='MpServer', x=194.50, y=68.00, z=21.50], EntityHorse['Horse'/119, l='MpServer', x=195.35, y=68.00, z=23.65], EntityHorse['Horse'/120, l='MpServer', x=191.50, y=67.00, z=23.50], EntityHorse['Horse'/121, l='MpServer', x=194.50, y=68.00, z=19.50], EntityHorse['Horse'/122, l='MpServer', x=196.68, y=68.00, z=22.32], EntityCow['Cow'/123, l='MpServer', x=186.50, y=66.00, z=18.50], EntityCow['Cow'/124, l='MpServer', x=187.58, y=67.12, z=21.45], EntityCow['Cow'/125, l='MpServer', x=192.10, y=69.00, z=12.54], EntityCow['Cow'/126, l='MpServer', x=188.52, y=67.00, z=21.50], EntityHorse['Horse'/131, l='MpServer', x=228.02, y=69.00, z=17.56], EntityHorse['Horse'/132, l='MpServer', x=231.50, y=69.00, z=14.50], EntityHorse['Horse'/133, l='MpServer', x=228.53, y=69.00, z=16.40], EntityHorse['Horse'/134, l='MpServer', x=228.50, y=69.00, z=15.17], EntityHorse['Horse'/135, l='MpServer', x=228.54, y=69.00, z=19.64], EntitySheep['Sheep'/136, l='MpServer', x=224.50, y=68.00, z=93.50], EntitySheep['Sheep'/137, l='MpServer', x=224.50, y=69.00, z=91.50], EntitySheep['Sheep'/138, l='MpServer', x=224.50, y=69.00, z=91.50], EntitySheep['Sheep'/139, l='MpServer', x=226.50, y=69.00, z=91.50], EntityBat['Bat'/4370, l='MpServer', x=190.81, y=43.81, z=139.39], EntityBat['Bat'/4382, l='MpServer', x=152.53, y=54.08, z=120.17], EntityZombie['Zombie'/4602, l='MpServer', x=200.50, y=32.00, z=35.50], EntityZombie['Zombie'/4735, l='MpServer', x=143.50, y=19.00, z=129.50], EntityCreeper['Creeper'/4736, l='MpServer', x=150.50, y=19.00, z=132.50], EntityBat['Bat'/4901, l='MpServer', x=227.55, y=18.81, z=21.52], EntityBat['Bat'/4903, l='MpServer', x=220.49, y=22.93, z=17.49], EntitySkeleton['Skeleton'/4927, l='MpServer', x=239.50, y=24.00, z=135.50], EntityCreeper['Creeper'/4928, l='MpServer', x=233.50, y=24.00, z=139.50], EntityCreeper['Creeper'/4929, l='MpServer', x=232.50, y=24.00, z=138.50], EntityEnderman['Enderman'/4963, l='MpServer', x=205.73, y=26.00, z=128.48], EntitySkeleton['Skeleton'/4964, l='MpServer', x=212.53, y=31.14, z=138.16], EntitySkeleton['Skeleton'/5164, l='MpServer', x=157.50, y=58.00, z=130.50], EntitySkeleton['Skeleton'/5203, l='MpServer', x=226.50, y=17.00, z=21.50], EntityEnderman['Enderman'/5277, l='MpServer', x=215.50, y=24.00, z=18.50], EntityBat['Bat'/5388, l='MpServer', x=118.14, y=40.03, z=120.54], EntityZombie['Zombie'/5413, l='MpServer', x=170.50, y=20.00, z=-6.50], EntitySkeleton['Skeleton'/5425, l='MpServer', x=214.27, y=18.00, z=15.50], EntityItem['item.item.seeds'/5457, l='MpServer', x=203.42, y=64.00, z=39.30], EntityCreeper['Creeper'/5477, l='MpServer', x=201.50, y=22.00, z=17.50], EntityCreeper['Creeper'/5478, l='MpServer', x=200.50, y=22.00, z=16.50], EntityCreeper['Creeper'/5547, l='MpServer', x=223.50, y=17.00, z=107.50], EntitySpider['Spider'/5548, l='MpServer', x=223.50, y=17.00, z=108.50], EntityZombie['Zombie'/5619, l='MpServer', x=199.50, y=22.00, z=18.50], EntityCreeper['Creeper'/5621, l='MpServer', x=199.50, y=22.00, z=19.50], EntityWitch['Witch'/5725, l='MpServer', x=152.50, y=55.00, z=122.50], EntityCreeper['Creeper'/5726, l='MpServer', x=153.50, y=55.00, z=121.50], EntityZombie['Zombie'/5727, l='MpServer', x=180.50, y=25.00, z=24.50], EntityPlayerSP['Zempat'/1759, l='MpServer', x=161.50, y=64.00, z=65.50], EntitySquid['Squid'/2212, l='MpServer', x=108.17, y=60.00, z=69.32], EntitySquid['Squid'/2213, l='MpServer', x=110.33, y=61.44, z=71.61]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 567810696 bytes (541 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | mw        | 0.4.1        | mw_2.0-0.4.1_mc1.12.2.jar     | None                                     |

	Loaded coremods (and transformers): 
weaponlib (mw_2.0-0.4.1_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.36' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.36, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz

**Comment by Timardo** [comment]
This is a client side crash. Are you sure Kettle is causing this? Have you tried the same set of mods on clean Forge server? Is there any error in the server log?

**Comment by Zempat** [comment]
I was using Forge 2838, i just need to use Optifine.
