### ISSUE TITLE
Having multiple problems :(

### ISSUE THREAD

**Issue by DolphinGamerYT** [KettleFoundation/Kettle#74]
Idk why but I'm having a lot of problems, I reviced the mods, but still isn't working. Here you have logs:

`Starting Kettle
[21:42:47] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[21:42:47] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[21:42:47] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[21:42:47] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2812 for Minecraft 1.12.2 loading
[21:42:47] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_212, running on Linux:amd64:5.0.0-1014-azure, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
[21:42:48] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[21:42:48] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[21:42:48] [main/INFO] [FML]: Searching /home/container/./mods for mods
[21:42:48] [main/INFO] [FML]: Searching /home/container/./mods/1.12.2 for mods
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AdvancedRocketry-1.12.2-1.6.0-160-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod AdvancedRocketryPlugin (zmaster587.advancedRocketry.asm.AdvancedRocketryPlugin) is not signed!
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.12.2-2.0.0.2.b165.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.10.19.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:48] [main/INFO] [Astral Core]: [AstralCore] Initialized.
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in bedpatch-2.2-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[21:42:48] [main/INFO] [FML]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.3.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:48] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.5-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:48] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.64+dev.146.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in librarianlib-1.12.2-4.19.2-release.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod com.teamwizardry.librarianlib.asm.LibLibCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:48] [main/WARN] [FML]: The coremod LibrarianLib Plugin (com.teamwizardry.librarianlib.asm.LibLibCorePlugin) is not signed!
[21:42:48] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.5.1.jar
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Mekanism-1.12.2-9.8.0.381.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod mekanism.coremod.MekanismCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:48] [main/WARN] [FML]: The coremod MekanismCoremod (mekanism.coremod.MekanismCoremod) is not signed!
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in NotEnoughIDs-1.5.4.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod ru.fewizz.neid.asm.Plugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:48] [main/WARN] [FML]: The coremod Plugin (ru.fewizz.neid.asm.Plugin) is not signed!
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in OpenComputers-MC1.12.2-1.7.4.153.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:48] [main/WARN] [FML]: The coremod li.cil.oc.common.launch.TransformerLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:48] [main/WARN] [FML]: The coremod TransformerLoader (li.cil.oc.common.launch.TransformerLoader) is not signed!
[21:42:48] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:49] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:49] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in p455w0rdslib-1.12.2-2.2.156.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:49] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:49] [main/WARN] [FML]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:49] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in wizardry-0.10.8.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:42:49] [main/WARN] [FML]: The coremod com.teamwizardry.wizardry.asm.WizardryCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:49] [main/WARN] [FML]: The coremod Wizardry Plugin (com.teamwizardry.wizardry.asm.WizardryCorePlugin) is not signed!
[21:42:49] [main/WARN] [FML]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:49] [main/WARN] [FML]: The coremod shetiphian.asm.TweakPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:49] [main/WARN] [FML]: The coremod ShetiPhian-ASM (shetiphian.asm.TweakPlugin) is not signed!
[21:42:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:42:49] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[21:42:49] [main/INFO] [LaunchWrapper]: Loading tweak class name codechicken.asm.internal.Tweaker
[21:42:49] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[21:42:49] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/home/container/./mods/malisiscore-1.12.2-6.5.1.jar Service=LaunchWrapper Env=SERVER
[21:42:49] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:42:49] [main/WARN] [FML]: The coremod MalisisCorePlugin (net.malisis.core.asm.MalisisCorePlugin) is not signed!
[21:42:49] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[21:42:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:42:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:42:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:42:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:51] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[21:42:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:51] [main/INFO] [Aroma1997Core]: Finished data injection.
[21:42:51] [main/INFO] [Aroma1997Core]: Finished data injection.
[21:42:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:51] [main/INFO] [LaunchWrapper]: Calling tweak class codechicken.asm.internal.Tweaker
[21:42:51] [main/INFO] [STDOUT]: [codechicken.asm.internal.Tweaker:injectIntoClassLoader:30]: false
[21:42:51] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[21:42:51] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@39ad12b6
[21:42:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:52] [main/INFO] [LaunchWrapper]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[21:42:52] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:42:52] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class
java.lang.ClassNotFoundException:
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:46) [kettle.jar:git-HEAD-0f5ecbf]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [kettle.jar:git-HEAD-0f5ecbf]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:35) [kettle.jar:git-HEAD-0f5ecbf]
Caused by: java.lang.NullPointerException
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
... 12 more
[21:42:52] [main/INFO] [Astral Core]: [AstralTransformer] Loading patches...
[21:42:53] [main/INFO] [Astral Core]: [AstralTransformer] Initialized! Loaded 14 class patches!
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:42:53] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:42:53] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[21:42:53] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[21:42:54] [main/INFO] [Astral Core]: [AstralTransformer] Transforming amu : net.minecraft.world.World with 2 patches!
[21:42:54] [main/INFO] [Astral Core]: [AstralTransformer] Skipping PATCHSUNBRIGHTNESSWORLDCLIENT as it can't be applied for side SERVER
[21:42:54] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHSUNBRIGHTNESSWORLDCOMMON
[21:42:54] [main/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:124]: Added INTERFACE: pl/asie/foamfix/coremod/patches/IFoamFixWorldRemovable
[21:42:54] [main/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:161]: Added METHOD: net.minecraft.world.World.foamfix_removeUnloadedEntities
[21:42:54] [main/INFO] [LibrarianLib ASM]: Transforming World
[21:42:54] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [updateEntities, func_72939_s] Descriptor ()V)
[21:42:54] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Update hook
[21:42:54] [main/INFO] [LibrarianLib ASM]: Patch result: Success
[21:42:54] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [updateEntityWithOptionalForce, func_72866_a] Descriptor (Lnet/minecraft/entity/Entity;Z)V)
[21:42:54] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Update hook
[21:42:54] [main/INFO] [LibrarianLib ASM]: Patch result: Success
[21:42:54] [main/INFO] [BedPatch]: Patching Chunk
[21:42:54] [main/INFO] [STDOUT]: [pl.asie.patchy.helpers.ConstructorReplacingTransformer$FFMethodVisitor:visitTypeInsn:73]: Replaced NEW for net/minecraft/util/ClassInheritanceMultiMap to pl/asie/foamfix/coremod/common/FoamyClassInheritanceMultiMap
[21:42:54] [main/INFO] [STDOUT]: [pl.asie.patchy.helpers.ConstructorReplacingTransformer$FFMethodVisitor:visitMethodInsn:85]: Replaced INVOKESPECIAL for net/minecraft/util/ClassInheritanceMultiMap to pl/asie/foamfix/coremod/common/FoamyClassInheritanceMultiMap
[21:42:54] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.pl.asie.foamfix.coremod.FoamFixTransformer' was detected and will no longer process meta class data
[21:42:54] [main/INFO] [Astral Core]: [AstralTransformer] Transforming pa : net.minecraft.network.NetHandlerPlayServer with 1 patches!
[21:42:54] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHSERVEREXTENDENTITYINTERACTREACH
[21:42:54] [main/INFO] [LibrarianLib ASM]: Transforming NetHandlerPlayServer
[21:42:54] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [update, func_73660_a] Descriptor ()V)
[21:42:54] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Update hook
[21:42:54] [main/INFO] [LibrarianLib ASM]: Patch result: Success
[21:42:54] [main/INFO] [Astral Core]: [AstralTransformer] Transforming amu : net.minecraft.world.World with 2 patches!
[21:42:54] [main/INFO] [Astral Core]: [AstralTransformer] Skipping PATCHSUNBRIGHTNESSWORLDCLIENT as it can't be applied for side SERVER
[21:42:54] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHSUNBRIGHTNESSWORLDCOMMON
[21:42:54] [main/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:124]: Added INTERFACE: pl/asie/foamfix/coremod/patches/IFoamFixWorldRemovable
[21:42:54] [main/INFO] [STDOUT]: [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:161]: Added METHOD: net.minecraft.world.World.foamfix_removeUnloadedEntities
[21:42:54] [main/INFO] [LibrarianLib ASM]: Transforming World
[21:42:54] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [updateEntities, func_72939_s] Descriptor ()V)
[21:42:54] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Update hook
[21:42:54] [main/INFO] [LibrarianLib ASM]: Patch result: Success
[21:42:54] [main/INFO] [LibrarianLib ASM]: Applying Transformation to method (Names [updateEntityWithOptionalForce, func_72866_a] Descriptor (Lnet/minecraft/entity/Entity;Z)V)
[21:42:54] [main/INFO] [LibrarianLib ASM]: Attempting to insert: Update hook
[21:42:54] [main/INFO] [LibrarianLib ASM]: Patch result: Success
[21:42:54] [main/INFO] [BetterFps]: Patching net.minecraft.block.Block... (aow)
[21:42:54] [main/INFO] [mixin]: A re-entrant transformer 'guichaguri.betterfps.transformers.PatcherTransformer' was detected and will no longer process meta class data
[21:42:54] [main/INFO] [neid]: Patching class: "net.minecraft.block.Block" with Transformer Group: "TransformerGroupBlockHardcoredConstants"
[21:42:54] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.ru.fewizz.neid.asm.Transformer' was detected and will no longer process meta class data
[21:42:54] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:230]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[21:42:54] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:242]: Transforming net.minecraft.block.Block Finished.
[21:42:55] [main/INFO] [STDOUT]: [com.teamwizardry.wizardry.asm.WizardryTransformer:log:35]: [wizardry ASM] Successfully patched -> 'func_70071_h_', 'onUpdate' with '()V'
A problem occurred running the Server launcher.[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: java.lang.reflect.InvocationTargetException
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: at java.lang.reflect.Method.invoke(Method.java:498)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:35]: at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:35)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Class.getDeclaredMethods0(Native Method)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Class.getMethod0(Class.java:3018)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at java.lang.Class.getMethod(Class.java:1784)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:42:55] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: ... 6 more
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: ... 13 more
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer squeek.applecore.asm.TransformerModuleHandler@79e7188e from coremod AppleCore
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: ... 15 more
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: java.lang.RuntimeException: No addExhaustion call (index=0) found in func_70665_d:
L0
LINENUMBER 1188 L0
ALOAD 0
ALOAD 1
FLOAD 2
INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayer.damageEntity_CB (Lnet/minecraft/util/DamageSource;F)Z
POP
L1
LINENUMBER 1189 L1
RETURN
L2
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: at squeek.applecore.asm.module.ModuleExhaustingActions.getAddExhaustionCall(ModuleExhaustingActions.java:185)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: at squeek.applecore.asm.module.ModuleExhaustingActions.getAddExhaustionCall(ModuleExhaustingActions.java:172)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: at squeek.applecore.asm.module.ModuleExhaustingActions.patchDamageEntity(ModuleExhaustingActions.java:153)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: at squeek.applecore.asm.module.ModuleExhaustingActions.transform(ModuleExhaustingActions.java:36)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:42)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
[21:42:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: ... 17 more`

**Comment by DolphinGamerYT** [comment]
[latest.log](https://github.com/KettleFoundation/Kettle/files/3664633/latest.log)
Here you have the latest.log

**Comment by GMatrixGames** [comment]
Kettle is being rewritten, please wait for an announcement for updates.
